language: php

php:
 - 7.2
 - 7.3

before_script:
# - pecl install channel://pecl.php.net/pthreads-3.1.6
 - echo | pecl install channel://pecl.php.net/yaml-2.0.4
 - git clone https://github.com/pmmp/pthreads.git
 - cd pthreads
 - git checkout 1b7da492b944146fa9680f6399bd9c6c6c6095e0
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
 - composer install
 - ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G
 - ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit
 - composer install --no-dev
 - ./tests/travis.sh -t4

notifications:
 email: false
