name: Fix code

on:
  push:
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml
        ini-values: post_max_size=256M, upload_max_filesize=256M

    - name: Install dependencies
      run: composer install

    - name: Run phpstan
      run: vendor/bin/phpstan analyse

    - name: Run php-cs-fixer
      run: vendor/bin/php-cs-fixer fix

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'GIBMGB Bot'
        git config --global user.email 'bot-email@example.com'
        git add .
        git commit -m "Auto fix by GIBMGB 🤖"
        git push
