name: Build And Upload

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Create XPocketMP.phar
      run: composer make-server

    - name: Upload XPocketMP.phar
      uses: actions/upload-artifact@v4
      with:
        name: XPocketMP (zip files)   
        path: ./XPocketMP.phar

