name: Build And Upload Debug

on:
  push:
    branches: [ "stables" ]
  pull_request:
    branches: [ "stables" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies and create XPocketMP.phar
      run: composer make-server

    - name: Upload debug XPocketMP
      uses: actions/upload-artifact@v4
      with:
        name: XPocketMP
        path: ./XPocketMP.phar
        
