name: Bump Version

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'Version to bump to (e.g., 5.21.2)'
        required: true
      api:
        description: 'API to bump to (e.g., 5)'
        required: false
      dev:
        description: 'Development build flag (e.g., true or false)'
        required: true

permissions:
  contents: write

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up GitHub App Authentication
        id: auth
        run: |
          npm install jsonwebtoken
          echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
          echo "${{ secrets.APP_PRIVATE_KEY }}" > private-key.pem
          JWT=$(node -e "
            const jwt = require('jsonwebtoken');
            const fs = require('fs');
            const privateKey = fs.readFileSync('private-key.pem');
            const payload = { appId: process.env.APP_ID };
            const token = jwt.sign(payload, privateKey, { algorithm: 'RS256', expiresIn: '10m' });
            console.log(token);
          ")
          echo "JWT=$JWT" >> $GITHUB_ENV

      - name: Get Installation Access Token
        id: token
        run: |
          INSTALLATION_TOKEN=$(curl -X POST https://api.github.com/app/installations/${{ secrets.APP_ID }}/access_tokens \
            -H "Authorization: Bearer ${{ env.JWT }}" \
            -H "Accept: application/vnd.github+json" \
            | jq -r .token)
          echo "INSTALLATION_TOKEN=$INSTALLATION_TOKEN" >> $GITHUB_ENV

      - name: Update Version in VersionInfo.php
        run: |
          # Update BASE_VERSION and API values
          sed -i "s/BASE_VERSION = \".*\";/BASE_VERSION = \"${{ github.event.inputs.new_version }}\";/g" src/VersionInfo.php
          if [[ -n "${{ github.event.inputs.api }}" ]]; then
            sed -i "s/API = \".*\";/API = \"${{ github.event.inputs.api }}\";/g" src/VersionInfo.php
          fi
          
          # Update IS_DEVELOPMENT_BUILD as a boolean without quotes
          sed -i "s/IS_DEVELOPMENT_BUILD = .*/IS_DEVELOPMENT_BUILD = ${{ github.event.inputs.dev }};/g" src/VersionInfo.php

      - name: Commit and Push Changes
        run: |
          git config --global user.name "XPocketMP[bot]"
          git config --global user.email "XPocketMP[bot]+${{ github.run_id }}@users.noreply.github.com"
          git add src/VersionInfo.php
          git commit -m "${{ github.event.inputs.new_version }} is next"
          
          # Use GitHub App Installation Token to Push
          curl -X POST -H "Authorization: Bearer ${{ env.INSTALLATION_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"message": "${{ github.event.inputs.new_version }} is next", "commits": [{"path": "src/VersionInfo.php", "content": "$(cat src/VersionInfo.php)", "sha": "$(git rev-parse HEAD)"}]}' \
            https://api.github.com/repos/${{ github.repository }}/contents/src/VersionInfo.php
