name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  all-php-versions:
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: ["8.1", "8.2", "8.3"]

    uses: ./.github/workflows/main-php-matrix.yml
    with:
      php: ${{ matrix.php }}
    secrets: inherit

  rector:
    name: Run Rector
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@3.2.0
        with:
          php-version: ${{ inputs.php }}
          install-path: "./bin"
          pm-version-major: ${{ inputs.pm-version-major }}

      - name: Restore Composer package cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ inputs.php }}-${{ hashFil>
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Rector
        run: php vendor/bin/rector process src

      - name: Run Rector 2
        run: php vendor/bin/rector process tests
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
