name: PHPStan and PHP-CS-Fixer

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Restore Composer package cache
      uses: actions/cache@v4
      with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ inputs.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G
        
    - name: Run PHPStan and PHP-CS-Fixer
      run: npm run fix
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Apply fixes by PHPStan and PHP-CS-Fixer'
        git push origin HEAD:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
