name: Update update.pmmp.io API info

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: sudo apt update && sudo apt install jq -y

      - uses: actions/checkout@v3
        with:
          repository: pmmp/update.pmmp.io
          ssh-key: ${{ secrets.UPDATE_PMMP_IO_DEPLOY_KEY }}

      - name: Get actual tag name
        id: tag-name
        run: echo TAG_NAME=$(echo "${{ github.ref }}" | sed 's{^refs/tags/{{') >> $GITHUB_OUTPUT

      - name: Download new release information
        run: curl -f -L ${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.tag-name.outputs.TAG_NAME }}/build_info.json -o new_build_info.json

      - name: Detect channels
        id: channel
        run: |
          CHANNEL=$(jq -r '.channel' new_build_info.json)
          VERSION=${{ steps.tag-name.outputs.TAG_NAME }}
          echo CHANNEL=$CHANNEL >> $GITHUB_OUTPUT
          if [ "$CHANNEL" == "stable" ]; then
            echo MAJOR=$(echo $VERSION | cut -d. -f1) >> $GITHUB_OUTPUT
            echo MINOR=$(echo $VERSION | cut -d. -f1-2) >> $GITHUB_OUTPUT
          else
            echo MAJOR=$(echo $VERSION | cut -d. -f1)-$CHANNEL >> $GITHUB_OUTPUT
            echo MINOR=$(echo $VERSION | cut -d. -f1-2)-$CHANNEL >> $GITHUB_OUTPUT
          fi

      - name: Update channel info
        run: |
          cp new_build_info.json "channels/${{ steps.channel.outputs.CHANNEL }}.json"
          cp new_build_info.json "channels/${{ steps.channel.outputs.MAJOR }}.json"
          cp new_build_info.json "channels/${{ steps.channel.outputs.MINOR }}.json"
          rm new_build_info.json

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "New ${{ steps.channel.outputs.CHANNEL }} release: ${{ github.repository }} ${{ steps.tag-name.outputs.TAG_NAME }}"

      - name: Push changes
        run: git push
