name: Update Code

on:
  pull_request:
  push:
  workflow_call:

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate access token   
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: RestrictedActions

    - name: Setup PHP
      uses: pmmp/setup-php-action@3.2.0
      with:
        php-version: 8.2
        install-path: "./bin"
 
    - name: Install PHP-CS-Fixer
      run: |
        wget https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.64.0/php-cs-fixer.phar -O /usr/local/bin/php-cs-fixer
        chmod +x /usr/local/bin/php-cs-fixer

    - name: Run PHP-CS-Fixer and Fix Code
      run: |
        php-cs-fixer fix --allow-risky=yes --quiet

    - name: UPDATE CODE GEN
      run: composer install --ignore-platform-req=* && composer update-codegen

    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}

    - name: Set Git config
      run: |
        git config user.name 'xpocketmp[bot]'
        git config user.email '${{ steps.get-user-id.outputs.user-id }}+xpocketmp[bot]@users.noreply.github.com'
        git add .
        git commit -m "Apply PHP-CS-Fixer changes" || echo "No changes to commit"

    - name: Push changes
      run: git push
