name: Update Code

on:
  pull_request:
  push:
  workflow_call:
    inputs:
      pm-version-major:
        description: 'PocketMine-MP major version'
        default: 5
        type: number

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode sumber dari repositori
    - name: Checkout repository
      uses: actions/checkout@v3

    # Generate GitHub App token
    - name: Generate GitHub App Token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}          # ID dari GitHub App Anda
        private_key: ${{ secrets.APP_PRIVATE_KEY }}  # Private key GitHub App Anda

    # Setup PHP
    - name: Setup PHP
      uses: pmmp/setup-php-action@3.2.0
      with:
        php-version: ${{ inputs.php }}
        install-path: "./bin"
        pm-version-major: ${{ inputs.pm-version-major }}
 
    # Install PHP-CS-Fixer
    - name: Install PHP-CS-Fixer
      run: |
        wget https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.64.0/php-cs-fixer.phar -O /usr/local/bin/php-cs-fixer
        chmod +x /usr/local/bin/php-cs-fixer

    # Jalankan PHP-CS-Fixer untuk memperbaiki kode
    - name: Run PHP-CS-Fixer and Fix Code
      run: |
        php-cs-fixer fix --allow-risky=yes --quiet

    - name: UPDATE CODE GEN
      run: composer install --ignore-platform-req=* && composer update-codegen

    # Commit dan push perubahan dengan token aplikasi
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: |
        git config --global user.name 'XPocketMP[bot]'
        git config --global user.email 'xpocketmp[bot]@xpocketmc.xyz'
        git add .
        git commit -m "Apply PHP-CS-Fixer changes" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
